### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by HebeiFast** [hexiaoxiao-cs/DMCVR#1]
作者能否提供一下数据集

**Comment by hexiaoxiao-cs** [comment]
Dear hbfast,

The datasets we used in this project comes from UK Biobank. Due to the agreement, we are not able to share the dataset publicly. However, you can access the dataset in this website: https://www.ukbiobank.ac.uk. 

For the segmentation ground truth, please check the UK Biobank Dataset 2158: 3-D Consistent and Robust Segmentation of Cardiac Images by Deep Learning With Spatial Propagation.

Best,
Xiaoxiao (Arist)
